"""add phone number

Revision ID: 4f17a18cd4fd
Revises: 9f594d6cfb03
Create Date: 2024-06-26 18:44:31.063603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f17a18cd4fd'
down_revision: Union[str, None] = '9f594d6cfb03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Likes', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('UserModel', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserModel', 'phone_number')
    op.drop_column('Likes', 'created_at')
    # ### end Alembic commands ###
