name: Build and deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: Production  # Specify the environment name here
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: check env
        run: echo ${{ secrets.HOST }}
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd app
            git pull
            pip install -r requirements.txt
            sudo systemctl restart app