name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: hello world
        run: echo "Hello World"